
package premierWebServiceClass.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.10
 * Thu Feb 09 10:58:31 CET 2017
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "ajouteResponse", namespace = "http://premierWebServiceClass/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ajouteResponse", namespace = "http://premierWebServiceClass/")

public class AjouteResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

