
package premierWebServiceClass.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.10
 * Thu Feb 09 10:58:31 CET 2017
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "recupereListResponse", namespace = "http://premierWebServiceClass/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recupereListResponse", namespace = "http://premierWebServiceClass/")

public class RecupereListResponse {

    @XmlElement(name = "return")
    private java.util.Collection<java.lang.String> _return;

    public java.util.Collection<java.lang.String> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.Collection<java.lang.String> new_return)  {
        this._return = new_return;
    }

}

