package premierwebserviceclass;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-09T11:06:56.171+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://premierWebServiceClass/", name = "MyServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface MyServiceImpl {

    @WebMethod
    @RequestWrapper(localName = "ajoute", targetNamespace = "http://premierWebServiceClass/", className = "premierwebserviceclass.Ajoute")
    @ResponseWrapper(localName = "ajouteResponse", targetNamespace = "http://premierWebServiceClass/", className = "premierwebserviceclass.AjouteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int ajoute(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "recupereList", targetNamespace = "http://premierWebServiceClass/", className = "premierwebserviceclass.RecupereList")
    @ResponseWrapper(localName = "recupereListResponse", targetNamespace = "http://premierWebServiceClass/", className = "premierwebserviceclass.RecupereListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> recupereList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
