
package premierwebserviceclass;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;

/**
 * This class was generated by Apache CXF 3.1.10 2017-02-09T11:06:56.102+01:00
 * Generated source version: 3.1.10
 * 
 */
public final class MyServiceImpl_MyServiceImplPort_Client {

	private static final QName SERVICE_NAME = new QName("http://premierWebServiceClass/", "MyServiceImplService");

	private MyServiceImpl_MyServiceImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = MyServiceImplService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		MyServiceImplService ss = new MyServiceImplService(wsdlURL, SERVICE_NAME);
		MyServiceImpl port = ss.getMyServiceImplPort();
		BindingProvider p = (BindingProvider) port;
		p.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "8081");
		{
			System.out.println("Invoking ajoute...");
			int _ajoute_arg0 = 1;
			int _ajoute_arg1 = 2;
			int _ajoute__return = port.ajoute(_ajoute_arg0, _ajoute_arg1);
			System.out.println("ajoute.result=" + _ajoute__return);

		}
		{
			System.out.println("Invoking recupereList...");
			java.lang.String _recupereList_arg0 = "_recupereList_arg015970766";
			java.lang.String _recupereList_arg1 = "_recupereList_arg11545104665";
			java.util.List<java.lang.String> _recupereList__return = port.recupereList(_recupereList_arg0,
					_recupereList_arg1);
			System.out.println("recupereList.result=" + _recupereList__return);

		}

		System.exit(0);
	}

}
